# Generated by Django 5.0.1 on 2026-02-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_video',
            field=models.FileField(blank=True, null=True, upload_to='articles/videos/', verbose_name='Відео (файл)'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Відео URL (YouTube/Vimeo)'),
        ),
    ]
